import {
  AlertApiDto,
  IotNodeApiDto,
  MachineryApiDto,
  MaintenanceRecordApiDto,
  TelemetryDataApiDto,
} from '../../shared/infrastructure/infratrack-api.contracts';
import { ControlPanelDashboardPayload } from './control-panel-dashboard.http';

const now = Date.now();
const hoursAgo = (h: number) => new Date(now - h * 3600_000).toISOString();
const daysAhead = (d: number) => new Date(now + d * 86400_000).toISOString().slice(0, 10);

export const CONTROL_PANEL_DEMO_PAYLOAD: ControlPanelDashboardPayload = {
  machinery: [
    {
      id: 1,
      operatorId: 1,
      plateNumber: 'BCP-204',
      model: 'FH16',
      brand: 'Volvo',
      fuelType: 'diesel',
      tankCapacityLiters: 400,
      currentStatus: 'active',
      imageUrl: '',
      createdAt: hoursAgo(720),
    },
    {
      id: 2,
      operatorId: 2,
      plateNumber: 'XYZ-918',
      model: '320D',
      brand: 'Caterpillar',
      fuelType: 'diesel',
      tankCapacityLiters: 280,
      currentStatus: 'active',
      imageUrl: '',
      createdAt: hoursAgo(600),
    },
    {
      id: 3,
      operatorId: 3,
      plateNumber: 'LIM-442',
      model: 'Actros',
      brand: 'Mercedes-Benz',
      fuelType: 'diesel',
      tankCapacityLiters: 350,
      currentStatus: 'active',
      imageUrl: '',
      createdAt: hoursAgo(480),
    },
    {
      id: 4,
      operatorId: 4,
      plateNumber: 'CAT-950',
      model: '950 GC',
      brand: 'Caterpillar',
      fuelType: 'diesel',
      tankCapacityLiters: 220,
      currentStatus: 'maintenance',
      imageUrl: '',
      createdAt: hoursAgo(900),
    },
    {
      id: 5,
      operatorId: 1,
      plateNumber: 'NOR-118',
      model: 'Actros',
      brand: 'Mercedes-Benz',
      fuelType: 'diesel',
      tankCapacityLiters: 380,
      currentStatus: 'active',
      imageUrl: '',
      createdAt: hoursAgo(300),
    },
  ],
  iotNodes: [
    {
      id: 1,
      machineryId: 1,
      nodeIdentifier: 'IOT-NODE-001',
      firmwareVersion: '2.4.1',
      batteryVoltage: 12.4,
      connectionStatus: 'online',
      lastSeen: hoursAgo(0.2),
    },
    {
      id: 2,
      machineryId: 2,
      nodeIdentifier: 'IOT-NODE-002',
      firmwareVersion: '2.4.1',
      batteryVoltage: 11.9,
      connectionStatus: 'online',
      lastSeen: hoursAgo(0.5),
    },
    {
      id: 3,
      machineryId: 3,
      nodeIdentifier: 'IOT-NODE-010',
      firmwareVersion: '2.3.8',
      batteryVoltage: 12.1,
      connectionStatus: 'online',
      lastSeen: hoursAgo(1),
    },
    {
      id: 4,
      machineryId: 4,
      nodeIdentifier: 'IOT-NODE-021',
      firmwareVersion: '2.4.0',
      batteryVoltage: 10.8,
      connectionStatus: 'offline',
      lastSeen: hoursAgo(6),
    },
    {
      id: 5,
      machineryId: 5,
      nodeIdentifier: 'IOT-NODE-022',
      firmwareVersion: '2.4.1',
      batteryVoltage: 12.6,
      connectionStatus: 'online',
      lastSeen: hoursAgo(0.3),
    },
  ],
  telemetryData: [
    {
      id: 1,
      nodeId: 1,
      fuelLevel: 288,
      fuelLevelPct: 72,
      latitude: -12.189,
      longitude: -76.982,
      engineHours: 1240,
      speedKmh: 38,
      engineOn: true,
      recordedAt: hoursAgo(0.2),
    },
    {
      id: 2,
      nodeId: 2,
      fuelLevel: 162,
      fuelLevelPct: 58,
      latitude: -12.195,
      longitude: -76.975,
      engineHours: 980,
      speedKmh: 0,
      engineOn: true,
      recordedAt: hoursAgo(0.4),
    },
    {
      id: 3,
      nodeId: 3,
      fuelLevel: 284,
      fuelLevelPct: 81,
      latitude: -12.098,
      longitude: -77.034,
      engineHours: 560,
      speedKmh: 22,
      engineOn: true,
      recordedAt: hoursAgo(0.8),
    },
    {
      id: 4,
      nodeId: 5,
      fuelLevel: 171,
      fuelLevelPct: 45,
      latitude: -11.991,
      longitude: -77.074,
      engineHours: 720,
      speedKmh: 55,
      engineOn: true,
      recordedAt: hoursAgo(0.3),
    },
  ],
  alerts: [
    {
      id: 1,
      machineryId: 2,
      type: 'fuel_theft',
      severity: 'critical',
      description: 'Caída de combustible del 9% en menos de 3 minutos — posible ordeño.',
      isAcknowledged: false,
      timestamp: hoursAgo(2),
    },
    {
      id: 2,
      machineryId: 5,
      type: 'fuel_theft',
      severity: 'warning',
      description: 'Consumo anómalo en ruta de despacho — revisar sensor de tanque.',
      isAcknowledged: false,
      timestamp: hoursAgo(5),
    },
    {
      id: 3,
      machineryId: 4,
      type: 'maintenance',
      severity: 'warning',
      description: 'Temperatura de motor elevada — unidad en taller.',
      isAcknowledged: true,
      timestamp: hoursAgo(8),
    },
    {
      id: 4,
      machineryId: 1,
      type: 'geofence',
      severity: 'warning',
      description: 'Volquete salió del perímetro de Obra Vía Sur.',
      isAcknowledged: false,
      timestamp: hoursAgo(12),
    },
  ],
  maintenanceRecords: [
    {
      id: 1,
      machineryId: 4,
      serviceType: 'general',
      description: 'Revisión sistema de refrigeración',
      costPen: 850,
      engineHoursAtService: 2100,
      serviceDate: daysAhead(-14),
      nextServiceDate: daysAhead(30),
    },
    {
      id: 2,
      machineryId: 1,
      serviceType: 'oil_change',
      description: 'Cambio de aceite y filtros',
      costPen: 420,
      engineHoursAtService: 1200,
      serviceDate: daysAhead(-21),
      nextServiceDate: daysAhead(45),
    },
  ],
};
